events {}

http {
    server {
        listen 80;

        location /openapi.yaml {
            alias /usr/share/nginx/html/openapi.yaml;
        }

        location /swagger/ {
            alias /usr/share/nginx/html/swagger/;
            try_files $uri $uri/ =404;
        }

        # ===== Статика =====
        location / {
            root /usr/share/nginx/html;
            try_files $uri $uri/ /index.html;
        }

        # ===== API — прокси на Tomcat =====
        location /currencies {
            proxy_pass http://app:8080;
            proxy_set_header Host $host;
        }

        location /currency/ {
            proxy_pass http://app:8080;
            proxy_set_header Host $host;
        }

        location /exchangeRates {
            proxy_pass http://app:8080;
            proxy_set_header Host $host;
        }

        location /exchangeRate/ {
            proxy_pass http://app:8080;
            proxy_set_header Host $host;
        }

        location /exchange {
            proxy_pass http://app:8080;
            proxy_set_header Host $host;
        }
    }
}