services:
  db:
    image: postgres:17-alpine
    restart: unless-stopped
    container_name: currency_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "127.0.0.1:5439:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    restart: unless-stopped
    container_name: currency_app
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - db

  frontend:
    build: ./frontend
    restart: unless-stopped 
    container_name: currency_front
    ports:
      - "80:80"
    depends_on:
      - app


volumes:
  pgdata: